stages:
  - test

variables:
  GIT_SUBMODULE_STRATEGY: normal

test:golangci-lint:
  stage: test
  image: golangci/golangci-lint:latest
  script:
    - golangci-lint run -v
  except:
    - tags
    - master
  tags:
    - hc-bladerunner
